/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ventanas;
import clases.cargarIDCliente;
import clases.conexionSql;
import static clases.conexionSql.ConnectDb;
import java.sql.*;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author robertito
 */
public class ventanaDebitos extends javax.swing.JFrame {
    JTable tDebitos;
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rss = null;
    ResultSet rsDatos = null;
    Connection con;
    ResultSet rs;
    Connection con1;
    ResultSet rs1;
    cargarIDCliente tCliente = new cargarIDCliente();
    public String id;
    /**
     * Creates new form ventanaDebitos
     */
    public ventanaDebitos() {
        initComponents();
        mostrarDatos();
        comboCargaIDCliente();        
        
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e){
                if(jTable1.getSelectedRow() != -1){
                    int fila = jTable1.getSelectedRow();
                    cboIDCliente.setSelectedItem(jTable1.getValueAt(fila, 0).toString());
                    txtNombre.setText(jTable1.getValueAt(fila, 1).toString());
                    txtMonto.setText(jTable1.getValueAt(fila, 2).toString());
                    txtEstado.setSelectedItem(jTable1.getValueAt(fila, 3).toString());
                }
            }            
        });
    }
    
    void mostrarDatos(){
        DefaultTableModel dm = new DefaultTableModel();
        tDebitos = this.jTable1;
        tDebitos.setModel(dm);
        
        dm.setColumnIdentifiers(new Object[]{"ID","NOMBRE","MONTO","ESTADO"});
        conexionSql con1 = new conexionSql();
        rs = con1.SeleccionarTodosDeudas();
        try {
            while(rs.next()){
                dm.addRow(new Object[]{rs.getString("id_cliente"), rs.getString("nombre"), rs.getString("monto_deuda"), rs.getString("estado_deuda")});
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnIngrDeuda = new javax.swing.JButton();
        btnElimDeuda = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnActDeuda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtMonto = new javax.swing.JTextField();
        txtEstado = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtBuscarCliente = new javax.swing.JTextField();
        btnBuscarDeuda = new javax.swing.JButton();
        cboIDCliente = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnIngrDeuda.setText("Ingresar Deuda");
        btnIngrDeuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngrDeudaActionPerformed(evt);
            }
        });

        btnElimDeuda.setText("Eliminar Deuda");
        btnElimDeuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimDeudaActionPerformed(evt);
            }
        });

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        btnActDeuda.setText("Actualizar Deuda");
        btnActDeuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActDeudaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Monto adeudado");

        jLabel3.setText("Estado de Deuda");

        txtEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Debe", "No debe" }));

        jLabel4.setText("ID");

        btnBuscarDeuda.setText("Buscar Deuda");
        btnBuscarDeuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDeudaActionPerformed(evt);
            }
        });

        cboIDCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboIDClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnIngrDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActDeuda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnElimDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cboIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarDeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnElimDeuda)
                    .addComponent(btnIngrDeuda)
                    .addComponent(btnActDeuda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarDeuda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conn = conexionSql.ConnectDb();
    }//GEN-LAST:event_formWindowOpened

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnIngrDeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngrDeudaActionPerformed
         String sql = "INSERT INTO deuda(id_cliente, nombre, monto_deuda, estado_deuda) VALUES (?, ?, ?, ?)";
        try {
            if(txtNombre.getText().length() != 0 ){
                pst = conn.prepareStatement(sql);
                pst.setString(1,cboIDCliente.getSelectedItem().toString());
                pst.setString(2,txtNombre.getText());               
                pst.setString(3,txtMonto.getText());
                pst.setString(4,txtEstado.getSelectedItem().toString());
                pst.executeUpdate();
                /*pst.executeBatch();*/
                if(pst!=null){
                    JOptionPane.showMessageDialog(null, "Datos ingresados correctamente");
                }else{
                    JOptionPane.showMessageDialog(null, "Error al ingresar datos");
                }
                txtNombre.setText("");
                mostrarDatos();
            }else{
                JOptionPane.showMessageDialog(null,"Ingrese datos");
                txtNombre.setText("");
                txtMonto.setText("");
            }
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_btnIngrDeudaActionPerformed

    private void btnBuscarDeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDeudaActionPerformed
        try {
            DefaultTableModel modeloDatos = null;
            String codBuscar = "";
            Connection con;
            con = conexionSql.ConnectDb();
            conexionSql con3 = new conexionSql();
            codBuscar = JOptionPane.showInputDialog("Ingrese codigo a buscar");
            rsDatos = con3.consulta("select id_cliente from deuda");
            boolean encontrado = false;
            while (rsDatos.next()){
                if(codBuscar.equals(rsDatos.getObject("codBuscar"))){
                    encontrado = true;
                    break;
                }
            }
            String SQL = "SELECT * FROM deuda WHERE id_cliente = "+codBuscar+"";
            modeloDatos = con3.retornarDatos(SQL);
            jTable1.setModel(modeloDatos);
            jScrollPane1.getViewport().add(jTable1);
            if(encontrado==false){
                JOptionPane.showMessageDialog(null, "No se encontro el codigo buscado");
            }            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarDeudaActionPerformed

    private void cboIDClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboIDClienteActionPerformed
        try {
            Statement sent1 = conn.createStatement();
            ResultSet rs1 = sent1.executeQuery("SELECT * FROM clientes WHERE id='"+this.cboIDCliente.getSelectedItem()+"'");
            rs1.next();
            String nombre = rs1.getString("nombre")+" "+rs1.getString("apellido");
            this.txtNombre.setText(String.valueOf(nombre));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cboIDClienteActionPerformed

    private void btnActDeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActDeudaActionPerformed
        String[] registro = {txtNombre.getText(), txtMonto.getText(), txtEstado.getSelectedItem().toString(), cboIDCliente.getSelectedItem().toString()};
        int opcion = conexionSql.actualizarRegistroDebitos(registro);
        if(opcion !=0){
            JOptionPane.showMessageDialog(this, "Registro agregado");
            mostrarDatos();
        }
    }//GEN-LAST:event_btnActDeudaActionPerformed

    private void btnElimDeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimDeudaActionPerformed
        int fila = jTable1.getSelectedRow();
        String cod = "";
        cod = jTable1.getValueAt(fila, 0).toString();
        try {
            pst = conn.prepareStatement("DELETE FROM deuda WHERE id_cliente = '"+cod+"'");
            pst.executeUpdate();
            mostrarDatos();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnElimDeudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaDebitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaDebitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaDebitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaDebitos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaDebitos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActDeuda;
    private javax.swing.JButton btnBuscarDeuda;
    private javax.swing.JButton btnElimDeuda;
    private javax.swing.JButton btnIngrDeuda;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox cboIDCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBuscarCliente;
    private javax.swing.JComboBox txtEstado;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void comboCargaIDCliente() {
        try {
            rs = tCliente.cargaIdCliente();
            while(rs.next()){
                cboIDCliente.addItem(rs.getString(1));
            }
        } catch (Exception e) {
        }
    }

 

}
